In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, precision_score,
    recall_score, f1_score, confusion_matrix
)

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [6]:
path = "../data/01_supermercados.csv"

df = pd.read_csv(path, sep=',', encoding='latin-1')

print(f'Tamanho da base: {df.shape[0]} registros e {df.shape[1]} variáveis')

print(f'Variáveis: {list(df.columns)}')

print(df.dtypes)

df.tail(10)

Tamanho da base: 9994 registros e 21 variáveis
Variáveis: ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object


Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
9984    9985  CA-2015-100251   5/17/2015   5/23/2015  Standard Class   
9985    9986  CA-2015-100251   5/17/2015   5/23/2015  Standard Class   
9986    9987  CA-2016-125794   9/29/2016   10/3/2016  Standard Class   
9987    9988  CA-2017-163629  11/17/2017  11/21/2017  Standard Class   
9988    9989  CA-2017-163629  11/17/2017  11/21/2017  Standard Class   
9989    9990  CA-2014-110422   1/21/2014   1/23/2014    Second Class   
9990    9991  CA-2017-121258   2/26/2017    3/3/2017  Standard Class   
9991    9992  CA-2017-121258   2/26/2017    3/3/2017  Standard Class   
9992    9993  CA-2017-121258   2/26/2017    3/3/2017  Standard Class   
9993    9994  CA-2017-119914    5/4/2017    5/9/2017    Second Class   

     Customer ID     Customer Name    Segment        Country         City  \
9984    DV-13465  Dianna Vittorini   Consumer  United States   Long Beach   
9985    DV-13465  Dianna Vittorini   Consumer  United States   Long Beach   
9986    ML-17410      Maris LaWare   Consumer  United States  Los Angeles   
9987    RA-19885      Ruben Ausman  Corporate  United States       Athens   
9988    RA-19885      Ruben Ausman  Corporate  United States       Athens   
9989    TB-21400  Tom Boeckenhauer   Consumer  United States        Miami   
9990    DB-13060       Dave Brooks   Consumer  United States   Costa Mesa   
9991    DB-13060       Dave Brooks   Consumer  United States   Costa Mesa   
9992    DB-13060       Dave Brooks   Consumer  United States   Costa Mesa   
9993    CC-12220      Chris Cortes   Consumer  United States  Westminster   

      ... Postal Code  Region       Product ID         Category Sub-Category  \
9984  ...       11561    East  OFF-LA-10003766  Office Supplies       Labels   
9985  ...       11561    East  OFF-SU-10000898  Office Supplies     Supplies   
9986  ...       90008    West  TEC-AC-10003399       Technology  Accessories   
9987  ...       30605   South  TEC-AC-10001539       Technology  Accessories   
9988  ...       30605   South  TEC-PH-10004006       Technology       Phones   
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings   
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings   
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones   
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper   
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances   

                                           Product Name    Sales  Quantity  \
9984                     Self-Adhesive Removable Labels   31.500        10   
9985  Acme Hot Forged Carbon Steel Scissors with Nic...   55.600         4   
9986  Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...   36.240         1   
9987  Logitech G430 Surround Sound Gaming Headset wi...   79.990         1   
9988                    Panasonic KX - TS880B Telephone  206.100         5   
9989                             Ultra Door Pull Handle   25.248         3   
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.960         2   
9991                              Aastra 57i VoIP phone  258.576         2   
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.600         4   
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.160         2   

      Discount   Profit  
9984       0.0  15.1200  
9985       0.0  16.1240  
9986       0.0  15.2208  
9987       0.0  28.7964  
9988       0.0  55.6470  
9989       0.2   4.1028  
9990       0.0  15.6332  
9991       0.2  19.3932  
9992       0.0  13.3200  
9993       0.0  72.9480  

[10 rows x 21 columns]

In [7]:
dados_nulos = df.isnull().sum()


tabela_nulos = pd.DataFrame({
    'Nome da Variável': dados_nulos.index,
    'Quantidade de Dados Nulos': dados_nulos.values
})


print(tabela_nulos)

   Nome da Variável  Quantidade de Dados Nulos
0            Row ID                          0
1          Order ID                          0
2        Order Date                          0
3         Ship Date                          0
4         Ship Mode                          0
5       Customer ID                          0
6     Customer Name                          0
7           Segment                          0
8           Country                          0
9              City                          0
10            State                          0
11      Postal Code                          0
12           Region                          0
13       Product ID                          0
14         Category                          0
15     Sub-Category                          0
16     Product Name                          0
17            Sales                          0
18         Quantity                          0
19         Discount                          0
20           

In [8]:
df['Order Date'] = pd.to_datetime(df['Order Date'], errors='coerce')
df['Ship Date'] = pd.to_datetime(df['Ship Date'], errors='coerce')

print("Datas não convertidas (nulos após conversão):")
print(df[['Order Date', 'Ship Date']].isnull().sum())

duplicatas = df.duplicated().sum()
print(f"Número de registros duplicados: {duplicatas}")
df = df.drop_duplicates()

categorias = ['Ship Mode', 'Segment', 'Country', 'Region', 'Category', 'Sub-Category']
for coluna in categorias:
    print(f"\nValores únicos em {coluna}:")
    print(df[coluna].value_counts())





print("\nValores únicos para 'Country':")
print(df['Country'].unique())

print("\nDescontos fora do padrão (esperado entre 0 e 0.8):")
print(df[df['Discount'] > 0.8])

print("\nValores negativos:")
print(df[(df['Sales'] < 0) | (df['Quantity'] < 0) | (df['Postal Code'] < 0)])

print("\nResumo dos dados após limpeza:")
print(df.info())

Datas não convertidas (nulos após conversão):
Order Date    0
Ship Date     0
dtype: int64
Número de registros duplicados: 0

Valores únicos em Ship Mode:
Ship Mode
Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: count, dtype: int64

Valores únicos em Segment:
Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

Valores únicos em Country:
Country
United States    9994
Name: count, dtype: int64

Valores únicos em Region:
Region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

Valores únicos em Category:
Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

Valores únicos em Sub-Category:
Sub-Category
Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Table

In [9]:



df['Profit_Positive'] = (df['Profit'] > 0).astype(int)


X = df[['Sales', 'Quantity', 'Discount']]
y = df['Profit_Positive']
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# Verificar tamanho dos conjuntos
print(f"Tamanho do conjunto de treino: {X_train.shape[0]} registros")
print(f"Tamanho do conjunto de teste: {X_test.shape[0]} registros")

# Verificar distribuição das classes
print("\nDistribuição das classes no treino:")
print(y_train.value_counts())

print("\nDistribuição das classes no teste:")
print(y_test.value_counts())

Tamanho do conjunto de treino: 6995 registros
Tamanho do conjunto de teste: 2999 registros

Distribuição das classes no treino:
Profit_Positive
1    5606
0    1389
Name: count, dtype: int64

Distribuição das classes no teste:
Profit_Positive
1    2452
0     547
Name: count, dtype: int64


In [ ]:
#regressao Logistica
modelo_lr = LogisticRegression(random_state=42)
modelo_lr.fit(X_train, y_train)
y_pred_lr = modelo_lr.predict(X_test)

print("\nRegressão Logística:")
print("Acurácia:", accuracy_score(y_test, y_pred_lr))
print("Precisão:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1-score:", f1_score(y_test, y_pred_lr))
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_lr))


#arvore de decisao
modelo_tree = DecisionTreeClassifier(random_state=42)
modelo_tree.fit(X_train, y_train)
y_pred_tree = modelo_tree.predict(X_test)

print("\nÁrvore de Decisão:")
print("Acurácia:", accuracy_score(y_test, y_pred_tree))
print("Precisão:", precision_score(y_test, y_pred_tree))
print("Recall:", recall_score(y_test, y_pred_tree))
print("F1-score:", f1_score(y_test, y_pred_tree))
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_tree))


#random forest
modelo_rf = RandomForestClassifier(n_estimators=100, random_state=42)
modelo_rf.fit(X_train, y_train)
y_pred_rf = modelo_rf.predict(X_test)

print("\nRandom Forest:")
print("Acurácia:", accuracy_score(y_test, y_pred_rf))
print("Precisão:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1-score:", f1_score(y_test, y_pred_rf))
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_rf))


#SVM
modelo_svm = SVC(kernel='linear', random_state=42)
modelo_svm.fit(X_train, y_train)
y_pred_svm = modelo_svm.predict(X_test)

print("\nSVM:")
print("Acurácia:", accuracy_score(y_test, y_pred_svm))
print("Precisão:", precision_score(y_test, y_pred_svm))
print("Recall:", recall_score(y_test, y_pred_svm))
print("F1-score:", f1_score(y_test, y_pred_svm))
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_svm))


#KNN
modelo_knn = KNeighborsClassifier(n_neighbors=5)
modelo_knn.fit(X_train, y_train)
y_pred_knn = modelo_knn.predict(X_test)

print("\nKNN:")
print("Acurácia:", accuracy_score(y_test, y_pred_knn))
print("Precisão:", precision_score(y_test, y_pred_knn))
print("Recall:", recall_score(y_test, y_pred_knn))
print("F1-score:", f1_score(y_test, y_pred_knn))
print("Matriz de Confusão:\n", confusion_matrix(y_test, y_pred_knn))


Regressão Logística:
Acurácia: 0.9369789929976658
Precisão: 0.93170545593285
Recall: 0.9959216965742251
F1-score: 0.9627439384979303
Matriz de Confusão:
 [[ 368  179]
 [  10 2442]]

Árvore de Decisão:
Acurácia: 0.9323107702567522
Precisão: 0.9569280780170663
Recall: 0.9604404567699837
F1-score: 0.9586810502747812
Matriz de Confusão:
 [[ 441  106]
 [  97 2355]]

Random Forest:
Acurácia: 0.934644881627209
Precisão: 0.9559417946645109
Recall: 0.9645187601957586
F1-score: 0.9602111246447422
Matriz de Confusão:
 [[ 438  109]
 [  87 2365]]
